# Generated by Django 5.2.10 on 2026-06-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLane',
            fields=[
                ('lane_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Lane Code')),
                ('lane_name', models.CharField(max_length=100, verbose_name='Lane Name')),
                ('vessel_service_type_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Vessel Service Type Code')),
                ('effective_from_date', models.DateField(blank=True, null=True, verbose_name='Effective start date of the lane.')),
                ('effective_to_date', models.DateField(blank=True, null=True, verbose_name='Effective end date of the lane.')),
                ('feeder_division_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Feeder Division Code')),
            ],
            options={
                'verbose_name': 'Master Lane',
                'verbose_name_plural': 'Master Lanes',
                'db_table': 'master_lane',
            },
        ),
        migrations.CreateModel(
            name='MasterPort',
            fields=[
                ('port_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Location Code')),
                ('port_name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('continent_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Continent Code')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'Master Port',
                'verbose_name_plural': 'Master Ports',
                'db_table': 'master_port',
            },
        ),
        migrations.CreateModel(
            name='MasterTrade',
            fields=[
                ('trade_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Trade Code')),
                ('trade_name', models.CharField(max_length=100, verbose_name='Trade Name')),
                ('from_continent_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='From Continent Code')),
                ('to_continent_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='To Continent Code')),
            ],
            options={
                'verbose_name': 'Master Trade',
                'verbose_name_plural': 'Master Trades',
                'db_table': 'master_trade',
            },
        ),
        migrations.CreateModel(
            name='DefaultCurrentProforma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacity')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Qty')),
                ('lane', models.ForeignKey(db_column='lane_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterlane', verbose_name='Lane Code / 3 alpha')),
                ('trade', models.ForeignKey(db_column='trade_code', on_delete=django.db.models.deletion.PROTECT, to='input.mastertrade', verbose_name='Trade Code')),
            ],
            options={
                'verbose_name': 'Default Current Proforma',
                'verbose_name_plural': 'DefaultCurrentProforma',
                'db_table': 'default_current_proforma',
            },
        ),
        migrations.CreateModel(
            name='DefaultBerthWindowStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('port', models.CharField(blank=True, max_length=20, null=True, verbose_name='Port')),
                ('berth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Berth')),
                ('etb_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETB Day')),
                ('etb_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETB Time')),
                ('etd_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETD Day')),
                ('etd_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETD Time')),
                ('loading_volume', models.IntegerField(blank=True, null=True, verbose_name='Loading Volume')),
                ('discharging_volume', models.IntegerField(blank=True, null=True, verbose_name='Discharging Volume')),
                ('productivity', models.IntegerField(blank=True, null=True, verbose_name='Productivity')),
                ('berthing', models.IntegerField(blank=True, null=True, verbose_name='Berthing')),
                ('lane', models.ForeignKey(db_column='lane_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterlane', verbose_name='Lane Code / 3 alpha')),
            ],
            options={
                'verbose_name': 'Default Berth Window Status',
                'verbose_name_plural': 'Default Berth Window Status',
                'db_table': 'default_berth_window_status',
            },
        ),
        migrations.CreateModel(
            name='DefaultProformaEssentialPort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_proforma', models.ForeignKey(db_column='proforma_id', on_delete=django.db.models.deletion.CASCADE, related_name='essential_ports', to='input.defaultcurrentproforma', verbose_name='Default Current Proforma ID')),
                ('port', models.ForeignKey(db_column='port_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterport', verbose_name='Port Code')),
            ],
            options={
                'verbose_name': 'Default Proforma Essential Port',
                'db_table': 'default_proforma_essential_port',
            },
        ),
        migrations.CreateModel(
            name='DefaultCurrentProformaDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terminal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Terminal')),
                ('etb_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETB Day')),
                ('etb_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETB Time')),
                ('etd_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETD Day')),
                ('etd_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETD Time')),
                ('current_proforma', models.ForeignKey(db_column='current_proforma_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='input.defaultcurrentproforma', verbose_name='Current Proforma ID')),
                ('port', models.ForeignKey(db_column='port_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterport', verbose_name='Port Code')),
            ],
            options={
                'verbose_name': 'Default Current Proforma Detail',
                'verbose_name_plural': 'Default Current Proforma Details',
                'db_table': 'default_current_proforma_detail',
            },
        ),
        migrations.CreateModel(
            name='DefaultRdrDemand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='RdrDemand ID')),
                ('demand_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Demand Value')),
                ('pod', models.ForeignKey(db_column='pod_code', on_delete=django.db.models.deletion.PROTECT, related_name='pod_demands', to='input.masterport')),
                ('pol', models.ForeignKey(db_column='pol_code', on_delete=django.db.models.deletion.PROTECT, related_name='pol_demands', to='input.masterport')),
                ('trade', models.ForeignKey(db_column='trade_code', on_delete=django.db.models.deletion.PROTECT, to='input.mastertrade', verbose_name='Trade Code')),
            ],
            options={
                'verbose_name': 'Default RDR Demand',
                'verbose_name_plural': 'Default RDR Demands',
                'db_table': 'default_rdr_demand',
                'ordering': ['trade', 'pol', 'pod'],
                'constraints': [models.UniqueConstraint(fields=('trade', 'pol', 'pod'), name='uq_trade_pol_pod')],
            },
        ),
        migrations.AddConstraint(
            model_name='defaultcurrentproforma',
            constraint=models.UniqueConstraint(fields=('trade', 'lane'), name='uq_trade_lane'),
        ),
    ]
