# Generated by Django 5.2.10 on 2026-06-29 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Simulation ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='진행률 (%)')),
                ('task_id', models.CharField(blank=True, help_text='Celery Task ID', max_length=255, null=True)),
                ('objective_value', models.FloatField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='실행 시간 (초)', null=True)),
                ('model_status', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulation Run',
                'db_table': 'simulation_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
