# Generated by Django 5.2.10 on 2026-07-01 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationProforma',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacity')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Qty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lane', models.ForeignKey(db_column='lane_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterlane', verbose_name='Lane Code / 3 alpha')),
                ('trade', models.ForeignKey(db_column='trade_code', on_delete=django.db.models.deletion.PROTECT, to='input.mastertrade', verbose_name='Trade Code')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Simulation Proforma',
                'db_table': 'simulation_proforma',
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Simulation ID')),
                ('simulation_number', models.CharField(blank=True, help_text='Auto-generated unique (YYYYMMDD_NN-XX)', max_length=20, unique=True, verbose_name='Simulation Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='진행률 (%)')),
                ('task_id', models.CharField(blank=True, help_text='Celery Task ID', max_length=255, null=True)),
                ('objective_value', models.FloatField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='실행 시간 (초)', null=True)),
                ('model_status', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('base_simulation_number', models.ForeignKey(blank=True, help_text='Reference Simulation Number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.simulationrun', verbose_name='Base Simulation Number')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Simulation Run',
                'db_table': 'simulation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationProformaEssentialPort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('port', models.ForeignKey(db_column='port_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterport', verbose_name='Port Code')),
                ('proforma', models.ForeignKey(db_column='proforma_id', on_delete=django.db.models.deletion.CASCADE, related_name='essential_ports', to='simulation.simulationproforma', verbose_name='Simulation Proforma ID')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='simulation.simulationrun', verbose_name='Simulation ID')),
            ],
            options={
                'verbose_name': 'Simulation Proforma Essential Port',
                'db_table': 'simulation_proforma_essential_port',
            },
        ),
        migrations.CreateModel(
            name='SimulationProformaDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terminal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Terminal')),
                ('calling_port_indicator', models.CharField(max_length=2, verbose_name='Port call order for each direction and port within the lane')),
                ('calling_port_seq', models.IntegerField(verbose_name='Port call sequence within the lane')),
                ('etb_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETB Day')),
                ('etb_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETB Time')),
                ('etd_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETD Day')),
                ('etd_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETD Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('port', models.ForeignKey(db_column='port_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterport', verbose_name='Port Code')),
                ('proforma', models.ForeignKey(db_column='proforma_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='simulation.simulationproforma', verbose_name='Simulation Proforma ID')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='simulation.simulationrun', verbose_name='Simulation ID')),
            ],
            options={
                'verbose_name': 'Simulation Proforma Detail',
                'verbose_name_plural': 'Simulation Proforma Details',
                'db_table': 'simulation_proforma_detail',
            },
        ),
        migrations.AddField(
            model_name='simulationproforma',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='simulation.simulationrun', verbose_name='Simulation ID'),
        ),
        migrations.CreateModel(
            name='SimulationBerthWindow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('port', models.CharField(blank=True, max_length=20, null=True, verbose_name='Port')),
                ('berth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Berth')),
                ('etb_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETB Day')),
                ('etb_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETB Time')),
                ('etd_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETD Day')),
                ('etd_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETD Time')),
                ('loading_volume', models.IntegerField(blank=True, null=True, verbose_name='Loading Volume')),
                ('discharging_volume', models.IntegerField(blank=True, null=True, verbose_name='Discharging Volume')),
                ('productivity', models.IntegerField(blank=True, null=True, verbose_name='Productivity')),
                ('berthing', models.IntegerField(blank=True, null=True, verbose_name='Berthing')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lane', models.ForeignKey(db_column='lane_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterlane', verbose_name='Lane Code / 3 alpha')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='simulation.simulationrun', verbose_name='Simulation ID')),
            ],
            options={
                'verbose_name': 'Simulation Berth Window',
                'verbose_name_plural': 'Simulation Berth Windows',
                'db_table': 'simulation_berth_window',
            },
        ),
        migrations.AddConstraint(
            model_name='simulationproforma',
            constraint=models.UniqueConstraint(fields=('simulation', 'trade', 'lane'), name='uq_simulation_trade_lane'),
        ),
    ]
