# Generated by Django 5.2.10 on 2026-06-29 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
        ('simulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.CreateModel(
            name='SimulationBerthWindow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country')),
                ('port', models.CharField(blank=True, max_length=20, null=True, verbose_name='Port')),
                ('berth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Berth')),
                ('etb_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETB Day')),
                ('etb_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETB Time')),
                ('etd_day', models.CharField(blank=True, max_length=10, null=True, verbose_name='ETD Day')),
                ('etd_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='ETD Time')),
                ('loading_volume', models.IntegerField(blank=True, null=True, verbose_name='Loading Volume')),
                ('discharging_volume', models.IntegerField(blank=True, null=True, verbose_name='Discharging Volume')),
                ('productivity', models.IntegerField(blank=True, null=True, verbose_name='Productivity')),
                ('berthing', models.IntegerField(blank=True, null=True, verbose_name='Berthing')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lane', models.ForeignKey(db_column='lane_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterlane', verbose_name='Lane Code / 3 alpha')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='simulation.simulationrun', verbose_name='Simulation ID')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Simulation Berth Window',
                'verbose_name_plural': 'Simulation Berth Windows',
                'db_table': 'simulation_berth_window',
            },
        ),
    ]
