# Generated by Django 5.2.10 on 2026-06-30 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_simulationrun_updated_by_simulationberthwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='base_simulation_number',
            field=models.ForeignKey(blank=True, help_text='Reference Simulation Number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.simulationrun', verbose_name='Base Simulation Number'),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='simulation_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique (YYYYMMDD_NN-XX)', max_length=20, unique=True, verbose_name='Simulation Number'),
        ),
    ]
