# Generated by Django 5.2.10 on 2026-06-30 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
        ('simulation', '0003_simulationrun_base_simulation_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationProforma',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacity')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Qty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lane', models.ForeignKey(db_column='lane_code', on_delete=django.db.models.deletion.PROTECT, to='input.masterlane', verbose_name='Lane Code / 3 alpha')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='simulation.simulationrun', verbose_name='Simulation ID')),
                ('trade', models.ForeignKey(db_column='trade_code', on_delete=django.db.models.deletion.PROTECT, to='input.mastertrade', verbose_name='Trade Code')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Simulation Proforma',
                'db_table': 'simulation_proforma',
                'constraints': [models.UniqueConstraint(fields=('simulation', 'trade', 'lane'), name='uq_simulation_trade_lane')],
            },
        ),
    ]
